---
title: "sanzo meets ggplot2"
author: "Jacqueline Maasch"
date: "12/18/2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(wesanderson)
library(RColorBrewer)
library(ggthemes)

raw <- read.csv("/Users/razel/Desktop/PROGS/R_practice/2019/sth_plasmid_ct_mean_raw.csv")

mean <- read.csv("/Users/razel/Desktop/PROGS/R_practice/2019/sth_plasmid_ct_mean.csv")

ct <- read.csv("/Users/razel/Desktop/PROGS/R_practice/2019/niger_giardia_swab_study_2019/niger_comparative_ct_by_duplicate.csv")

c171 <- c("#730f1f", "#ff8c00", "#b3e8c2")
c174 <- c("#ffa6d9", "#bfabcc", "#6b2e63")
c207 <- c("#9b5348", "#b3e8c2", "#000000")
c232 <- c("#d60036", "#f2ad78", "#000831")
```

## ggplot2 demos

### sanzo duos

```{r duos}

```

### sanzo trios

```{r trios}
ggplot(mean, aes(fill = Concentration, y = CT, x = Target)) + 
  geom_bar(position = "dodge", stat = "identity") +
  theme_tufte() +
  scale_color_manual(values = c171) +
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        legend.title = element_text(size = 10)) +
  labs (y= "CT VALUE MEAN\n", 
        x = "\nTARGET GENUS", 
        fill = "PLASMID CONCENTRATION", 
        title = "MEAN PLASMID CONTROL CT VALUE BY qPCR TARGET\n")



ggplot(mean, aes(fill = Concentration, y = CT, x = Target)) + 
  geom_bar(stat = "identity") +
  theme_few() +
  scale_color_manual(values = c174) + 
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        legend.title = element_text(size = 10)) +
  labs (y= "CT VALUE MEAN\n", 
        x = "\nTARGET GENUS", 
        fill = "PLASMID CONCENTRATION", 
        title = "MEAN PLASMID CONTROL CT VALUE BY qPCR TARGET\n")



ggplot(raw, aes(CT1, CT2, color = as.factor(Concentration))) + 
  geom_point(aes(shape = Target),
             size = 2, 
             alpha = 3/4) +
  geom_rug() + 
  theme_tufte(ticks = FALSE) + 
  scale_color_manual(name = "PLASMID CONCENTRATION", 
                     values = c239) + 
  scale_shape_manual(name = "TARGET", 
                     values = c207) + 
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        legend.title = element_text(size = 10)) +
  labs (y= "CT REPLICATE 2\n", 
        x = "\nCT REPLICATE 1", 
        fill = "TARGET", 
        title = "MEAN PLASMID CONTROL CT VALUE BY qPCR TARGET\n") + 
  geom_smooth(method = lm, 
              se = FALSE, 
              color = "darkslategray", 
              size = 0.5) +
  scale_y_continuous(limits = c(15, 35)) + 
  scale_x_continuous(limits = c(15, 35)) +
  geom_abline(intercept = 0, 
              slope = 1, 
              linetype = "dotted",
              color = "ivory3")



ggplot(raw, aes(CT1, CT2, color = as.factor(Concentration))) + 
  geom_point(aes(shape = Target), 
             size = 2,
             alpha = 3/4) + 
  theme_few() + 
  scale_color_manual(name = "PLASMID CONCENTRATION", 
                     values = c232) + 
  scale_shape_manual(name = "TARGET", 
                     values = c232) + 
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        legend.title = element_text(size = 10)) +
  labs (y= "CT REPLICATE 2\n", 
        x = "\nCT REPLICATE 1", 
        fill = "TARGET", 
        title = "MEAN PLASMID CONTROL CT VALUE BY qPCR TARGET\n") + 
  geom_smooth(method = lm, 
              se = FALSE, 
              color = "darkslategray", 
              size = 0.5) +
  scale_y_continuous(limits = c(15, 35)) + 
  scale_x_continuous(limits = c(15, 35)) +
  geom_abline(intercept = 0, 
              slope = 1, 
              linetype = "dotdash", 
              color = "seashell3", 
              size = 0.3)
```

### sanzo quads
```{r quads}

```
